// Literal expected outputs from 6tail/lunar-typescript EightCharTest.ts.
// Source commit f086189a0b159cd5d71d1b23090ccf034444fa04.
// Inverse fromBaZi fixtures are used in the forward direction; never generated by our wrapper.
export const baziFixtures = [
  {
    date: "2005-12-23",
    time: "08:37",
    expected: ["乙酉", "戊子", "辛巳", "壬辰"],
    source: "test1",
  },
  {
    date: "1988-02-15",
    time: "23:30",
    expected: ["戊辰", "甲寅", "庚子", "戊子"],
    source: "test2",
  },
  {
    date: "1988-02-15",
    time: "22:30",
    expected: ["戊辰", "甲寅", "庚子", "丁亥"],
    source: "test3",
  },
  {
    date: "1988-02-02",
    time: "22:30",
    expected: ["丁卯", "癸丑", "丁亥", "辛亥"],
    source: "test4",
  },
  {
    date: "1976-09-21",
    time: "12:00",
    expected: ["丙辰", "丁酉", "丙子", "甲午"],
    source: "16",
  },
  {
    date: "1999-07-21",
    time: "16:00",
    expected: ["己卯", "辛未", "甲戌", "壬申"],
    source: "17",
  },
  {
    date: "1960-12-17",
    time: "12:00",
    expected: ["庚子", "戊子", "己卯", "庚午"],
    source: "18",
  },
  {
    date: "2020-07-21",
    time: "22:00",
    expected: ["庚子", "癸未", "乙丑", "丁亥"],
    source: "19",
  },
  {
    date: "2023-02-25",
    time: "00:00",
    expected: ["癸卯", "甲寅", "甲寅", "甲子"],
    source: "20",
  },
  {
    date: "1960-01-15",
    time: "16:00",
    expected: ["己亥", "丁丑", "壬寅", "戊申"],
    source: "21",
  },
  {
    date: "1959-12-17",
    time: "16:00",
    expected: ["己亥", "丙子", "癸酉", "庚申"],
    source: "22",
  },
  {
    date: "1997-03-12",
    time: "18:00",
    expected: ["丁丑", "癸卯", "癸丑", "辛酉"],
    source: "23",
  },
];
